project_id = "kbxijzsrywcwnyvtbruh"

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.get-signed-url]
verify_jwt = false

[functions.create-discord-invite]
verify_jwt = false

[functions.notify-designer]
verify_jwt = false

[functions.generate-monthly-report]
verify_jwt = false

[functions.calculate-talent-score]
verify_jwt = false
