// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// <define:import.meta.env>
var define_import_meta_env_default = { MODE: "production", BASE_URL: "/", DEV: false, PROD: true, SSR: false };

// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's Prime Haven profile: name, email, role, and (for designers) points/salary snapshot.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [profileRes, roleRes, designerRes] = await Promise.all([
      supabase.from("profiles").select("id,email,full_name,is_active,created_at").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId).maybeSingle(),
      supabase.from("designer_details").select("professional_title,professions,total_points,monthly_points,salary_estimated").eq("user_id", userId).maybeSingle()
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail(),
      profile: profileRes.data ?? null,
      role: roleRes.data?.role ?? null,
      designer: designerRes.data ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-my-submissions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_submissions_default = defineTool2({
  name: "list_my_submissions",
  title: "List my submissions",
  description: "List the signed-in designer's recent submissions with status, points, and creation date. Optional status filter.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Max rows"),
    status: z.enum(["pending", "ph_approved", "client_accepted", "approved", "revision", "rejected"]).optional().describe("Filter by submission status")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let q = supabase.from("submissions").select("id,project_name,status,points_awarded,created_at,ph_approved,rejection_reason").eq("designer_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-notifications.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_notifications_default = defineTool3({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "Return the signed-in user's most recent notifications.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(10),
    unread_only: z2.boolean().default(false)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, unread_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let q = supabase.from("notifications").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (unread_only) q = q.eq("is_read", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-open-job-contracts.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_open_job_contracts_default = defineTool4({
  name: "list_open_job_contracts",
  title: "List open job contracts",
  description: "List Prime Haven job contracts that are still open for designers to claim. Optional category filter.",
  inputSchema: {
    category: z3.string().optional().describe("Optional category filter (e.g. 'graphic-design')"),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data: rows, error } = await supabase.rpc("get_open_job_contracts");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const data = (rows ?? []).filter((r) => !category || r.category === category).slice(0, limit).map((r) => ({
      id: r.id,
      title: r.title,
      category: r.category,
      description: r.description,
      budget: r.budget,
      deadline: r.deadline,
      active_designers_count: r.active_designers_count
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = define_import_meta_env_default.VITE_SUPABASE_PROJECT_ID ?? "project-ref-unset";
var mcp_default = defineMcp({
  name: "prime-haven-mcp",
  title: "Prime Haven",
  version: "0.1.0",
  instructions: "Tools for the Prime Haven creative platform. Use `get_my_profile` to identify the signed-in user, `list_my_submissions` to review a designer's recent submissions, `list_my_notifications` for their inbox, and `list_open_job_contracts` to discover jobs available to claim.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_my_submissions_default, list_my_notifications_default, list_open_job_contracts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
