-- ============================================
-- PRIME HAVEN - CLIENT UX RLS SCHEMA UPDATES
-- Generated by Antigravity (April 2026)
-- Run this in your Supabase SQL Editor
-- ============================================

-- 1. Drop existing permissive logic on submissions to cleanly inject new ones
DROP POLICY IF EXISTS "Clients can view their submitted deliverables" ON public.submissions;
DROP POLICY IF EXISTS "Clients can accept deliverables" ON public.submissions;

-- 2. Add Select Policy allowing authenticated clients to safely read submissions linked to their email
-- This uses client_orders as the bridge since submissions uses 'client_ref'
CREATE POLICY "Clients can view their submitted deliverables" 
ON public.submissions 
FOR SELECT 
TO authenticated
USING (
  client_ref IN (SELECT id::text FROM public.client_orders WHERE client_email = (auth.jwt() ->> 'email'))
);

-- 3. Add Update Policy allowing clients to mark submissions as accepted
CREATE POLICY "Clients can accept deliverables" 
ON public.submissions 
FOR UPDATE 
TO authenticated
USING (
  client_ref IN (SELECT id::text FROM public.client_orders WHERE client_email = (auth.jwt() ->> 'email'))
)
WITH CHECK (
  client_ref IN (SELECT id::text FROM public.client_orders WHERE client_email = (auth.jwt() ->> 'email'))
  AND ph_approved = true -- Security: Can only accept after PH QA approves
);

-- 4. Enable RLS on System Logs for Client actions if restricted
DROP POLICY IF EXISTS "Clients can insert system logs" ON public.system_logs;
CREATE POLICY "Clients can insert system logs" 
ON public.system_logs 
FOR INSERT 
TO authenticated
WITH CHECK (
  auth.uid() = admin_id 
  AND action_type = 'client_acceptance'
);

-- Note: Ensure designer_details total points/monthly points updates still work. 
-- Standard RESTRICTIVE policies for "Designers can update their own details" might block clients from awarding points to designers directly on the client side.
-- If clients fail to award points due to designer_details RLS blocking them (since they aren't the designer),
-- create a quick security definer function to handle point allocation safely.

CREATE OR REPLACE FUNCTION allocate_client_acceptance_points(p_designer_id uuid, p_points integer)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER -- Execution under db owner bypasses RLS safely
AS $$
BEGIN
  UPDATE public.designer_details 
  SET 
    total_points = COALESCE(total_points, 0) + p_points,
    monthly_points = COALESCE(monthly_points, 0) + p_points,
    updated_at = now()
  WHERE user_id = p_designer_id;
END;
$$;
