ALTER TABLE public.applicants
  ADD COLUMN IF NOT EXISTS integrity_flags integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS integrity_status text;

INSERT INTO public.assessment_tasks (track, title, brief, submission_type, is_active) VALUES
('Mobile App Development','Simple app screen','Build or design a single mobile app screen: a task list with an add-item action, an empty state, and a loading state. Share a repo link, an Expo/preview link, or a design file link. Explain your state handling in a sentence or two.','either',true),
('Motion Graphics','5-second logo sting','Animate a simple wordmark (real or invented) into a 5-second logo sting with a clean in and out. Share a link to the rendered video (Drive, YouTube unlisted, Vimeo) plus a one-line note on your timing choices.','either',true),
('Video Editing','30-second highlight cut','Using any footage you have rights to, cut a 30-second highlight reel with titles, music, and clean audio levels. Share a link to the export and a one-line note on your pacing choices.','either',true),
('General IT Solutions','Small network brief','A 12-person studio has flaky Wi-Fi, no backups, and shared passwords. Write a short plan (max 400 words) covering what you would fix first, the tools you would use, and rough monthly cost. Paste the text or share a document link.','either',true);

INSERT INTO public.assessment_questions (track, question_type, prompt, options, correct_option, points, is_active) VALUES
('Mobile App Development','multiple_choice','Which framework lets you ship one JavaScript codebase to both iOS and Android?','["React Native","Swift UI","Jetpack Compose","WinUI"]',0,1,true),
('Mobile App Development','multiple_choice','What is the main purpose of an app''s splash screen?','["Cover the launch gap while the app initialises","Store user data","Handle push notifications","Compress images"]',0,1,true),
('Mobile App Development','multiple_choice','Which store review issue most often delays an iOS release?','["Missing privacy details or permission justification","Using dark mode","Too many screenshots","Having a settings page"]',0,1,true),
('Mobile App Development','multiple_choice','What does "offline-first" mean in mobile app design?','["The app works from local data and syncs when online","The app refuses to run without Wi-Fi","The app disables all network calls","The app only works in airplane mode"]',0,1,true),
('Mobile App Development','multiple_choice','Which tool is used for over-the-air updates in an Expo React Native app?','["EAS Update","Gradle","Xcode Instruments","Figma"]',0,1,true),
('Mobile App Development','multiple_choice','What is the recommended minimum touch target size on mobile?','["About 44-48px","12px","8px","100px"]',0,1,true),
('Mobile App Development','multiple_choice','Where should an API secret key live in a mobile app?','["On a server the app calls","Hardcoded in the app bundle","In AsyncStorage","In the app''s README"]',0,1,true),
('Mobile App Development','multiple_choice','Which of these causes the most common Android crash reports?','["Unhandled null references and lifecycle misuse","Using too many colours","Large fonts","Portrait orientation"]',0,1,true),
('Mobile App Development','multiple_choice','What does a "cold start" measure?','["Time from tapping the icon to a usable screen","Battery usage overnight","Download size","Server latency only"]',0,1,true),
('Mobile App Development','multiple_choice','Which is the correct way to persist a login session on a device?','["Secure storage / keychain","Plain text file in Downloads","A global variable","URL query string"]',0,1,true),
('Mobile App Development','multiple_choice','What is a deep link used for?','["Opening a specific screen in the app from a URL","Encrypting the database","Reducing bundle size","Animating transitions"]',0,1,true),
('Mobile App Development','multiple_choice','Which practice keeps long lists smooth on low-end devices?','["Virtualised lists that render only visible rows","Rendering every row at once","Using larger images","Disabling scrolling"]',0,1,true),
('Mobile App Development','multiple_choice','Why use a staged rollout on the Play Store?','["Limit the blast radius of a bad release","Speed up review","Avoid paying fees","Skip testing"]',0,1,true),
('Mobile App Development','multiple_choice','What does the safe area inset protect against?','["Notches, status bars and home indicators","Slow networks","Small screens only","Dark mode"]',0,1,true),
('Mobile App Development','multiple_choice','Which is best for syncing app state with a backend in real time?','["A websocket or realtime subscription","Polling every 10 minutes","Manual refresh only","Email updates"]',0,1,true),
('Mobile App Development','multiple_choice','A client asks for an app in two weeks with an unclear scope. Best first move?','["Agree a small, shippable v1 scope in writing","Start coding immediately","Quote double and hope","Decline all work"]',0,1,true),

('Motion Graphics','multiple_choice','Which principle makes motion feel natural rather than robotic?','["Easing","Constant linear speed","Random keyframes","Zero motion blur"]',0,1,true),
('Motion Graphics','multiple_choice','What does a pre-composition do in After Effects?','["Groups layers so they can be treated as one","Renders the final file","Deletes keyframes","Converts video to audio"]',0,1,true),
('Motion Graphics','multiple_choice','Which frame rate is standard for most social video?','["30fps","12fps","96fps","240fps"]',0,1,true),
('Motion Graphics','multiple_choice','What is a style frame?','["A still that sets the look before animating","The last frame of a render","A colour profile","A font file"]',0,1,true),
('Motion Graphics','multiple_choice','Which format is best for a web animation with transparency and tiny file size?','["Lottie (JSON)","AVI","BMP sequence","WAV"]',0,1,true),
('Motion Graphics','multiple_choice','What does "overshoot" add to an animation?','["A slight pass beyond the target before settling","Extra render time","Audio distortion","Colour banding"]',0,1,true),
('Motion Graphics','multiple_choice','Why use a null object as a parent?','["Control several layers with one transform","Add sound","Increase resolution","Export faster"]',0,1,true),
('Motion Graphics','multiple_choice','Kinetic typography mainly relies on which two things?','["Timing and hierarchy","Gradients and noise","3D cameras and fog","Audio compression"]',0,1,true),
('Motion Graphics','multiple_choice','What is the graph editor used for?','["Fine-tuning velocity between keyframes","Managing project files","Colour grading","Rendering audio"]',0,1,true),
('Motion Graphics','multiple_choice','Which aspect ratio suits a full-screen vertical reel?','["9:16","16:9","1:1","4:3"]',0,1,true),
('Motion Graphics','multiple_choice','Why is motion blur important in fast moves?','["It reduces strobing and reads smoother","It shrinks file size","It brightens footage","It fixes audio sync"]',0,1,true),
('Motion Graphics','multiple_choice','What does a track matte let you do?','["Use one layer''s shape or luminance to reveal another","Duplicate a comp","Convert to vector","Export a still"]',0,1,true),
('Motion Graphics','multiple_choice','Which codec is commonly used to deliver a high-quality intermediate master?','["ProRes","GIF","MP3","PNG"]',0,1,true),
('Motion Graphics','multiple_choice','How long should a logo sting typically be?','["3-6 seconds","30 seconds","2 minutes","Under 0.5 seconds"]',0,1,true),
('Motion Graphics','multiple_choice','What is sound design''s role in motion graphics?','["It reinforces impact and timing of the visuals","It replaces animation","It is only for film","It reduces render time"]',0,1,true),
('Motion Graphics','multiple_choice','A client sends a low-resolution logo for a 4K animation. Best response?','["Request a vector or high-res original","Upscale and hope","Redraw without telling them","Cancel the job"]',0,1,true),

('Video Editing','multiple_choice','What is a J-cut?','["Audio leads the incoming shot","Video leads the audio","A jump cut","A colour transition"]',0,1,true),
('Video Editing','multiple_choice','Which loudness level is a common target for online video?','["Around -14 LUFS","0 LUFS","-60 LUFS","+6 LUFS"]',0,1,true),
('Video Editing','multiple_choice','What is the purpose of a rough cut?','["Lock story and pacing before polish","Deliver the final file","Colour grade","Add captions"]',0,1,true),
('Video Editing','multiple_choice','Which tool removes steady background hum from dialogue?','["A noise reduction / de-noise effect","A crossfade","A lumetri curve","A speed ramp"]',0,1,true),
('Video Editing','multiple_choice','What does log footage need before delivery?','["A LUT or manual grade","Nothing at all","Only sharpening","Only captions"]',0,1,true),
('Video Editing','multiple_choice','Why check the safe margins on a vertical edit?','["Platform UI can cover edges","It improves colour","It reduces bitrate","It syncs audio"]',0,1,true),
('Video Editing','multiple_choice','What is B-roll used for?','["Cover cuts and add context","Replace the main audio","Fix exposure","Set frame rate"]',0,1,true),
('Video Editing','multiple_choice','Which export container is safest for client review links?','["MP4 (H.264)","MKV","MXF","RAW"]',0,1,true),
('Video Editing','multiple_choice','What does a speed ramp do?','["Gradually change clip speed for emphasis","Fade audio only","Crop the frame","Lock white balance"]',0,1,true),
('Video Editing','multiple_choice','Why use proxies when editing 4K on a modest machine?','["Smooth playback with lighter files","Better colour","Smaller final export","Faster upload only"]',0,1,true),
('Video Editing','multiple_choice','Captions matter most because...','["Most social video is watched muted","They shrink file size","They improve colour","They speed rendering"]',0,1,true),
('Video Editing','multiple_choice','What is the 180-degree rule about?','["Keeping consistent screen direction between subjects","Camera exposure","Audio phase","Colour temperature"]',0,1,true),
('Video Editing','multiple_choice','Which is the right fix for clipped, distorted audio?','["Re-record or replace the take","Boost the gain","Add reverb","Increase bitrate"]',0,1,true),
('Video Editing','multiple_choice','What does a scopes panel help you judge?','["Exposure and colour accurately","Audio levels","Render time","File naming"]',0,1,true),
('Video Editing','multiple_choice','Best practice for versioning client edits?','["Clear numbered versions with change notes","Overwrite the same file","Rename randomly","Keep one file only"]',0,1,true),
('Video Editing','multiple_choice','A client asks for a 5th round of revisions beyond scope. Best response?','["Flag scope politely and quote the extra round","Refuse to reply","Do it all free forever","Deliver a rough cut instead"]',0,1,true),

('Social Media Management','multiple_choice','Which metric best shows content resonance rather than reach?','["Engagement rate","Impressions","Follower count","Post count"]',0,1,true),
('Social Media Management','multiple_choice','What is a content pillar?','["A recurring theme that guides posts","A paid ad format","A scheduling tool","A hashtag limit"]',0,1,true),
('Social Media Management','multiple_choice','Why does a content calendar matter?','["It keeps posting consistent and on-strategy","It boosts the algorithm directly","It replaces analytics","It writes captions"]',0,1,true),
('Social Media Management','multiple_choice','Best first step when taking over a new client account?','["An audit of past performance and audience","Post immediately","Buy followers","Change the handle"]',0,1,true),
('Social Media Management','multiple_choice','What does a strong hook in the first 3 seconds do?','["Stops the scroll and earns watch time","Improves resolution","Adds hashtags","Boosts follower count directly"]',0,1,true),
('Social Media Management','multiple_choice','Which is the healthiest way to grow an account?','["Consistent value-led content plus community replies","Follow/unfollow loops","Engagement pods only","Buying likes"]',0,1,true),
('Social Media Management','multiple_choice','How should you handle a negative public comment from a real customer?','["Reply calmly and move it to DM or email","Delete it silently","Argue publicly","Ignore forever"]',0,1,true),
('Social Media Management','multiple_choice','What is UGC?','["User-generated content","Universal graphic code","Unpaid growth campaign","Upload gate check"]',0,1,true),
('Social Media Management','multiple_choice','Which report figure would a client care about most?','["Leads or enquiries generated","Number of hashtags used","Time spent editing","Emoji count"]',0,1,true),
('Social Media Management','multiple_choice','What does A/B testing a caption tell you?','["Which message drives more action","Which image is sharper","The best posting app","Follower demographics"]',0,1,true),
('Social Media Management','multiple_choice','Why tailor a post per platform instead of cross-posting identically?','["Formats and audience behaviour differ","It costs less","It avoids copyright","Algorithms ban reposts"]',0,1,true),
('Social Media Management','multiple_choice','What is social listening?','["Monitoring mentions and conversations about a brand","Adding music to reels","Podcast editing","Voice notes in DMs"]',0,1,true),
('Social Media Management','multiple_choice','A post unexpectedly goes viral. What should you do first?','["Engage replies fast and point traffic to an offer","Delete and repost","Stop posting","Change the bio"]',0,1,true),
('Social Media Management','multiple_choice','Which cadence is most defensible for a small business starting out?','["3-5 quality posts a week","20 posts a day","One post a month","Only stories"]',0,1,true),
('Social Media Management','multiple_choice','What belongs in a monthly analytics report?','["Growth, engagement, top posts and next-month actions","Only follower count","Screenshots with no context","Nothing, clients dislike numbers"]',0,1,true),
('Social Media Management','multiple_choice','Client wants to post something factually wrong about a competitor. Best response?','["Push back and propose a compliant alternative","Post it as asked","Post it anonymously","Ignore the request"]',0,1,true),

('General IT Solutions','multiple_choice','What does the 3-2-1 backup rule mean?','["3 copies, 2 media types, 1 offsite","3 servers, 2 admins, 1 password","3 backups a day","3 firewalls in series"]',0,1,true),
('General IT Solutions','multiple_choice','Which is the strongest single improvement to account security?','["Multi-factor authentication","Longer usernames","Monthly password rotation","Disabling autofill"]',0,1,true),
('General IT Solutions','multiple_choice','What is the purpose of a VLAN?','["Segment network traffic logically","Increase internet speed","Encrypt email","Back up files"]',0,1,true),
('General IT Solutions','multiple_choice','A user cannot reach any website but can ping an IP. Likely cause?','["DNS misconfiguration","Broken monitor","Full disk","Expired antivirus"]',0,1,true),
('General IT Solutions','multiple_choice','What does RAID 1 provide?','["Mirrored redundancy","Extra capacity only","Backup offsite","Encryption"]',0,1,true),
('General IT Solutions','multiple_choice','Which practice reduces phishing risk the most across a team?','["Training plus MFA and email filtering","Longer passwords only","Blocking all attachments","Disabling Wi-Fi"]',0,1,true),
('General IT Solutions','multiple_choice','What is the point of least privilege?','["Users get only the access they need","Everyone gets admin","No one gets access","Access expires daily"]',0,1,true),
('General IT Solutions','multiple_choice','Which log would you check first for repeated failed logins?','["Authentication / security log","Printer queue","Browser history","DNS cache"]',0,1,true),
('General IT Solutions','multiple_choice','What does patch management protect against?','["Known exploited vulnerabilities","Power cuts","Hardware theft","Slow Wi-Fi"]',0,1,true),
('General IT Solutions','multiple_choice','Wi-Fi is slow in one corner of an office. Best first check?','["Signal strength, channel overlap and AP placement","Replace all laptops","Reinstall Windows","Buy a new router blindly"]',0,1,true),
('General IT Solutions','multiple_choice','Why use a password manager for a team?','["Unique strong credentials with safe sharing","It is cheaper than email","It disables MFA","It speeds up the network"]',0,1,true),
('General IT Solutions','multiple_choice','What is an RTO in a recovery plan?','["Target time to restore service","Rate of traffic output","Remote terminal option","Router timing offset"]',0,1,true),
('General IT Solutions','multiple_choice','Which is true of cloud backups?','["They still need restore testing","They never fail","They replace security","They are always cheapest"]',0,1,true),
('General IT Solutions','multiple_choice','A staff laptop is stolen. First action?','["Revoke sessions and remote-wipe the device","Buy a replacement","Change the office Wi-Fi name","Do nothing"]',0,1,true),
('General IT Solutions','multiple_choice','What does an SSL/TLS certificate provide?','["Encrypted, verified connections","Faster downloads","Virus scanning","Backups"]',0,1,true),
('General IT Solutions','multiple_choice','Client refuses to pay for backups after a scare. Best professional move?','["Document the risk in writing and offer a low-cost tier","Set it up secretly","Walk away without notice","Blame the staff"]',0,1,true);